### ISSUE TITLE
Флай хак какой-то кривой

### ISSUE THREAD

**Issue by Dramorian** [Kramar1337/Tower-of-Fantasy-AHK-flex#1]
Нажимаешь на него, а он потом не отжимается.

**Comment by Kramar1337** [comment]
по хорошему бы заполнить описание к скрипту, но мне впадлу.
Скрипт тупо спамит гаджет
забиндить джетпак в настройках скрипта tofuConfig.ini => key_flyhackGajetKey(там краткое описание есть)

4 - Абузный полет(зажать кнопку и типа медленно падаешь не тратя стамину)

V - Macro Key
+
Numpad 3 - AutoFlyHack (первый клик - вкл, повторный клик - выкл)
Esc - Остановить потоки
End - Завершить работу AHK
PgUp - Приостановить - возобновить работу AHK

нампад клавой выбираешь скрипт и макро кей активирует, первое нажатие запускает поток, повторное нажатие останавливает поток. нужно находиться в воздухе в момент активации. на китае когда играл пролетал так всю карту по вертикали с парка аттракционов до конца старт острова.
скрипт по сути залипает кнопку "W", спамит гаджет и делает рывки каждые 4 сек. скрипт сам будет лететь вперед, просто в воздухе нажать 1 кнопку
