### ISSUE TITLE
suggestion add frigg jetpack macro

### ISSUE THREAD

**Issue by Gigachad694200** [Kramar1337/Tower-of-Fantasy-AHK-flex#10]
I saw that there is a frigg jetpack for the link you provided on dps calculations and it says that (assumes jetpack macro tech) in the notes.

**Comment by Kramar1337** [comment]
I did not think about it and checked.
Alt + Numpad 2 - Karasuma drill
works with FRIGG

**Comment by Kramar1337** [comment]
checked the damage on a Chinese client on a training dummy. Damage is very low. I don't understand where "355.88" comes from in the table
