### ISSUE TITLE
Working in inactive window

### ISSUE THREAD

**Issue by Be4Die** [Kramar1337/Tower-of-Fantasy-AHK-flex#11]
Hi, do you plan to make some functions work when the game window is minimized or inactive or unfocused?

**Comment by Kramar1337** [comment]
Currently available:
1 - *CS AFK farming, spam "F" every 5 sec
2 - *CS AFK surfer's achievement, sticking of the "W" and "A" buttons
3 - *CS AFK farming on Hilda, spam "Click" every 3 sec (Honey Farm? Mounts?)
4 - *CS AFK farming, spam "F" sticking buttons "W" and "A". Garnet Farm(-75, -845)
5 - *CS AFK farming, spam "F" walking in circles "W" and "S", 5 seconds forward, 5 seconds back

The "ControlSend" send method (which works in an inactive window) will be fixed someday. This has been fixed on the Chinese client. The possibilities of "ControlSend" are limited, I do not want to develop this direction.

I am using "vmware workstation" for virtualization. I start the virtual machine => I start the game in it => I start the Frontier farm script => I go to play other games on the main system \ do my own thing.

I don't plan to add new scripts to work in idle window mode.
