### ISSUE TITLE
Frontier position 6

### ISSUE THREAD

**Issue by Phatlynx** [Kramar1337/Tower-of-Fantasy-AHK-flex#12]
frontier clash is now in position 6 due to new event.

**Comment by Kramar1337** [comment]
page switching does not work correctly.
The script maximizes the list of activities and selects 5 or 6 items.
I added the option "9" and "10" (before last and last).

**Comment by Shanlayz** [comment]
hi , i use 9 and 10 but it didnt work . no option for now ?

**Comment by Kramar1337** [comment]
forgot how to move the cursor to AHK, fixed the frontier
