### ISSUE TITLE
Failed to open Adventure tab

### ISSUE THREAD

**Issue by TakaraEnj** [Kramar1337/Tower-of-Fantasy-AHK-flex#13]
Keeps failing to open the adventure tab when trying to afk frontier

**Comment by Kramar1337** [comment]
I don't understand, need more information.

Playing in full screen or borderless mode?
What is the screen resolution?

You select the Arrows mode - "7" and press "F4"
What happens next?

ps The script can't miss the "adventure" tab, it just presses the "Alt" button and presses "3"
Alt+1 2 3 4 hidden game hotkeys, do they work for you?

**Comment by TakaraEnj** [comment]
Ah I see, I tried pressing alt + 1 2 3 4 and they do not work. How do I fix this?
The script was working fine a few days ago but I did not change any game settings. 

I am playing in 1920 x 1080, fullscreen.

**Comment by Kramar1337** [comment]
I do not know.
Reinstall game?

**Comment by TakaraEnj** [comment]
Solid copy, thanks
