### ISSUE TITLE
FRIGG Shift+Click to fast

### ISSUE THREAD

**Issue by yopichy** [Kramar1337/Tower-of-Fantasy-AHK-flex#14]
Delay between shift and click to fast, so if hosting v button, FRIGG only dodge not hit

**Comment by Kramar1337** [comment]
I don't play Frigga, I need a lot of testing.
increased latency from 15ms to 50ms

**Comment by yopichy** [comment]
@Kramar1337 still same too fast, on my logitech macro, i'm set like this work perfectly.
Need to add 1 shift and 2 click.

I'll edited your changes and PR later
![image](https://user-images.githubusercontent.com/2038089/191288108-4c932dda-5d61-45b9-b1ab-bcb713a68583.png)

**Comment by Kramar1337** [comment]
I have changed the code according to the screenshot. Check
