### ISSUE TITLE
Скрипт тупит или мне так кажется...

### ISSUE THREAD

**Issue by Dramorian** [Kramar1337/Tower-of-Fantasy-AHK-flex#17]
1. С последней обновой постоянно внизу экрана вижу уведомление о том, что "нельзя сесть на маунта в таком состоянии", находясь в бою, когда тыкаю макро-клавишу на V. Раньше такого не было.
Вне боя перс на долю секунды его призывает и соскакивает, следовательно те же автоатаки Самир с numpad1 начинаются с воздуха. Понимаю, что в конфиге и в игре можно перебиндить, но я уже за месяц с лишним привык.

2. Зачем дэш спам? Мешает.

**Comment by Kramar1337** [comment]
2. Можно отключить в "tofuConfig.ini"
1. Задумка была такой что и макрос и маунт биндятся на 1 кнопку, но при прожатии "Shift" кнопка не блокируется и все равно срабатывает. Я отключил блокировку кнопки скриптом и теперь мой вариант использования:
Макрос на "V"
Маунт на "С"
В игре эти кнопки разбиндить

**Comment by Edoktongl2** [comment]
![สกรีนช็อต 2022-09-28 212936](https://user-images.githubusercontent.com/114595193/192806269-d45589f6-ec63-4909-b99b-79c53aacc95c.png)

**Comment by Edoktongl2** [comment]
![image](https://user-images.githubusercontent.com/114595193/192806353-0b79c887-319f-4da3-8323-93353fbab0d2.png)

**Comment by Kramar1337** [comment]
the script recognizes the text in English and clicks on the appropriate buttons. Other languages are not supported.

But you can use the manual method.
In the config file
"FrontierTextSearch=0"

**Comment by Kramar1337** [comment]
the script recognizes the text in English and clicks on the appropriate buttons. Other languages are not supported.

But you can use the manual method.
In the config file
"FrontierTextSearch=0"

**Comment by Edoktongl2** [comment]
> 

I don't know if I have to change English. Thank you very much. We really don't know.   Thank you for further development.
