### ISSUE TITLE
Only AFK Funcs

### ISSUE THREAD

**Issue by Dayil** [Kramar1337/Tower-of-Fantasy-AHK-flex#18]
I would like to disable most functions and leave only AFK modes enabled. Further reducing the chance of ban. Because the other functions don't interest me.
I could just ignore the functions, not hit the shortcut button. But I'm afraid of accidentally pressing some function and activating it without consent.

**Comment by Kramar1337** [comment]
at the very bottom of the configuration file there is an option to disable script functions
