### ISSUE TITLE
Frigg Delay

### ISSUE THREAD

**Issue by chaderfooster** [Kramar1337/Tower-of-Fantasy-AHK-flex#19]
Would it be possible to delay the frigg's auto attack a little because I feel like we end up losing damage by being too fast.

Numpad-6 ( Frigg shift+click )

**Comment by Kramar1337** [comment]
I don't play Frigga and don't know what timings are best. I was given ready-made timings and I added them. If you have ready-made timings that are superior to the current ones, give them to me.
