### ISSUE TITLE
[Предложение] Макрос для Хумы

### ISSUE THREAD

**Issue by Dramorian** [Kramar1337/Tower-of-Fantasy-AHK-flex#2]
https://youtu.be/65pO6xIZakU?t=119

**Comment by Kramar1337** [comment]
на глобале нету хумы, потестил на китае, кароч, пробуй

V - Macro Key

Numpad 4 - Huma combo t1
Numpad 5 - Huma combo t2

**Comment by Dramorian** [comment]
> на глобале нету хумы, потестил на китае, кароч, пробуй
> 
> V - Macro Key
> 
> Numpad 4 - Huma combo t1 Numpad 5 - Huma combo t2

Изредка в воздух поднимается на первом комбо, а так отлично работает.

**Comment by Kramar1337** [comment]
у мя на китае тренировочный кактус норм тыкается в мирор сити, ничего не поднимается в воздух
можешь покалибровать тайминги
761 строка если норм блокнот или поиск по тексту "Label_Goto_HumaV1:" без кавычек, менять "Sleep 600" задержки в мс

кста на счетчике урона разницы с макросом или просто спам руками, я не увидел
; 29к кактус 30 сек спам лкм и шифта
; 29.5к кактус 30 сек макрос 1 400
; 30к кактус 30 сек макрос 2 800
; 30к кактус 30 сек макрос без отмены прыжком

на глобале другие множители, мож по этому, хз

**Comment by Dramorian** [comment]
> у мя на китае тренировочный кактус норм тыкается в мирор сити, ничего не поднимается в воздух

это было связано с тем, что я бил на неровной поверхности, в частности на спуске
