### ISSUE TITLE
Фарм Фронтира

### ISSUE THREAD

**Issue by Dramorian** [Kramar1337/Tower-of-Fantasy-AHK-flex#21]
1. Желательно сделать кд поменьше между действиями.
2. На этапе с рубильником вбегает в стену (Разрешение 1280х720 в фуллскрине)

**Comment by Kramar1337** [comment]
не оч понял что не так с кд? в начале игры все были слабые и чистка фронтира занимала много времени и + на виртуалке долго прогружается игра по этому время с запасом. (я про общее время всего цикла)
Если речь о других действиях то все ок даже на медленной виртуалке с фпс локом 10фпс.

Рубильник кривой, я перепутал места но менять ничего не стал, в целом норм играет, расчет на то что никто не начнет по этому он долго ждет иначе ктото другой нажмет и скрипт забагается. Респ всегда разный и иногда может промахиваться, я делал несколько прогонов всегда попадает, но обычно другой чел прожимает рубильник.
Мне бы видос как скрипт вбегает в стену чтобы я понимал при каких условиях это происходит. Сам скрипт не идеален и я не стал доводить его до совершенства по тому что там долгий путь и фронтир не самое профитное место для фарма если так подумать. Нада потестить фарм порталов там раз в 70 заходов крутку в стандарт дают... хз

Кароч у меня норм играет и на основе "25фпс 1440п" и на виртуалке "10фпс 720п" фуллскрин естесна. Нужен фулл вбегания в стену
