### ISSUE TITLE
Запрос функций / Features Request

### ISSUE THREAD

**Issue by RXDCODX** [Kramar1337/Tower-of-Fantasy-AHK-flex#23]
1. Прошу поменять бинд F1 в котором будет гайд по хоткеям и биндам скрипта 
2. Хоткей интерактивной карты поставить на F3
3. Автоходьбу поставить на другую кнопку (F5 как пример)
4. Если возможно - на F12 засунуть скрипт который предложит самому назначить хоткеи с нуля или сделать по умолчанию

**Comment by Kramar1337** [comment]
для назначения кнопок есть конфиг "data\tofuConfig.ini", можно перебиндить так как хочется.

подсказка с хоткеями... хз из простого я мог бы добавить в оверлей скрин гитхаба: кнопку нажал - вылезла подсказка. Но зачем, если можно просто альтабнуться и посмортеть.

**Comment by nokhen** [comment]
Возможность афк фарма фронтира без попыток.
Скрипт ищет фронтир, но когда нет попыток, фронтир находится за экраном (нужно сделать слайд вправо)
