### ISSUE TITLE
Not an Issue but a request

### ISSUE THREAD

**Issue by Eliatshaha** [Kramar1337/Tower-of-Fantasy-AHK-flex#24]
_(no idea why I can't pull requests sorry :c)_ 
There are some new macros you could include if you want, [Lin's one](https://www.youtube.com/watch?v=SiNaSr4MjXo&ab_channel=Kentoloupe) is pretty simple but usefull, there are many others in that channel too If you wanna take a look

**Comment by Kramar1337** [comment]
I found 2 videos on the channel: Lin and Ruby.
I don’t have Ruby’s character, but I have Lin’s character, so I only added a macro with Lin

Alt + Numpad 0 - Lin hold
