### ISSUE TITLE
Fishing is not fully working.

### ISSUE THREAD

**Issue by Skullmonkey** [Kramar1337/Tower-of-Fantasy-AHK-flex#25]
Hello and thank you for the work you have done so far.

I am not able to get the afk fishing to fully work. It will not start fishing or reel in the fish automatically. The portion where you have to keep it in the yellow is working fine.

For example, I have to click on the fishing button in the bottom right to start the fishing. After that, the bot does its thing but when the fish is ready to be reeled in, I have to click the button. It also does not cast out again.

**Comment by Kramar1337** [comment]
Hello.
My fishing works without problems.
Checked on:
Main computer 1440p 90fps
virtual machine 720p 30fps
I cast the bait and the script itself finds the yellow strip and catches the fish itself and casts the bait again.
I use the standard rod and standard bait and fish on the starting island.
Sometimes landscape colors and fishing colors merge and the script misses, but usually everything works fine.

I increased the color range and capture area and put the settings in "tofuConfig.ini".

**Comment by Kramar1337** [comment]
Try increasing the setting

; Fishing. color scatter
PixelFisRange=3

**Comment by LilTrublMakr** [comment]
I play 3440x1440 @90FPS on the global client. Also using standard rod and bait.

 I have tried all of the 1440 resolutions with no success at the starting spot in Astra Shelter and the 2 spots up the river. All of them work for the yellow part but will not auto cast or retrieve. What spot  are you fishing from?

Maybe if you can outline where you are scanning for the color, I can grab a screenshot and try to see if I can find the color in there and modify it to get it to work.

**Comment by Skullmonkey** [comment]
I play 3440x1440 90fps on the global client. Also using standard rod and bait.

I have tried all of the 1440 resolutions with no success at the starting spot in Astra Shelter and the 2 spots up the river. All of them work for the yellow part but will not auto cast or retrieve. What spot are you fishing from?

Maybe if you can outline where you are scanning for the color, I can grab a screenshot and try to see if I can find the color in there and modify it to get it to work.

**Comment by Kramar1337** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/73392036/209580724-7aa90b32-7be2-498b-8910-a03e9bf180ef.png)
PixelFisPix=0x8CFFFF

**Comment by Kramar1337** [comment]
heh, I get it. ultrawide monitor

**Comment by Kramar1337** [comment]
the script uses the formula

and it works for 16-9 ratio
I don't know how to do for 21-9

**Comment by Kramar1337** [comment]
I need a screenshot of the game while fishing on your monitor.

**Comment by Skullmonkey** [comment]
![Screenshot 2022-12-26 145058](https://user-images.githubusercontent.com/396053/209581741-4760b8f5-63c1-4830-a432-d6d3bce40cf5.png)
Black areas are my status bar and window I had open so I could SS. I labeled the upper left and lower right locations of each of the areas of interest for you. For the 8CFFFF location, I marked the pixel position that I can find the lowest of.

**Comment by Kramar1337** [comment]
increased range. update the script and try again

**Comment by Skullmonkey** [comment]
Working perfectly now!
