### ISSUE TITLE
Lyra God Mode

### ISSUE THREAD

**Issue by prix2play** [Kramar1337/Tower-of-Fantasy-AHK-flex#26]
How does it work? It does a short uppercut for the attack but it's not hitting any enemies. TIA

**Comment by Kramar1337** [comment]
https://www.reddit.com/r/TowerofFantasy/comments/ztpx48/lyra_rejects_any_damage_with_her_accumulator_skill/

**Comment by Kramar1337** [comment]
this macro does not deal damage but allows you to survive the deadly attack of the enemy

**Comment by prix2play** [comment]
Got it! Thank you sir!
