### ISSUE TITLE
Frontier Clash script a little off

### ISSUE THREAD

**Issue by eculipseNamae** [Kramar1337/Tower-of-Fantasy-AHK-flex#27]
Frontier clash script when accepting match is a little off, the cursor doesn't hit accept. It's just a little bit above accept.
How do I modify frontier clash x and y so that I can change it to hit accept.

P.S. I don't understand russian, ty for all your work on ToF macros.

**Comment by Kramar1337** [comment]
what is your screen resolution? and aspect ratio?

**Comment by Kramar1337** [comment]
i changed the coordinates, update the script and check

**Comment by eculipseNamae** [comment]
> i changed the coordinates, update the script and check

Thank you! It's working fine now, cursor is now accurate.
