### ISSUE TITLE
Fishing (left reel)

### ISSUE THREAD

**Issue by djoeni** [Kramar1337/Tower-of-Fantasy-AHK-flex#28]
compared to right reel (D), left reel (A) seem sluggish/late especially on purple fish... left reel wont catch yellow bar while right reel perfectly match.
maybe because my screen resolution is 1440x900 or something?

**Comment by Kramar1337** [comment]
try experimenting with the options:

; Fishing. Distance calibration. If close to the left edge then increase the value. Default 20
FisCalibration=50

; Fishing. Antishake
FisAntishake=10

**Comment by djoeni** [comment]
problem solved with lowering  FisCalibration to 10. thanks
