### ISSUE TITLE
[Question] on shiro annihilation

### ISSUE THREAD

**Issue by eculipseNamae** [Kramar1337/Tower-of-Fantasy-AHK-flex#29]
Sorry not really an issue. But I wanted to know how exactly does shiro annihilation work? How do you do it manually? I can't seem to find any sources of how to do it.

**Comment by Kramar1337** [comment]
manually will not come out, there is a delay of 0 ms, you need to press hit and jump at the same time

SendInput, {vk20} 	;Space
Sleep 0
SendInput, {vk1} 	;LButton

**Comment by Kramar1337** [comment]
I accidentally found a video on reddit, it was a long time ago, I lost the link

**Comment by Kramar1337** [comment]
it looks like this
Loop
{
	SendInput, {vk20} 	;Space
	Sleep 0
	SendInput, {vk1} 	;LButton
	Sleep 165
	SendInput, {vk1 Down} 	;LButton
	Sleep 310 	;700 min - 740 old
	Sleep 400
	SendInput, {vk1 Up} 	;LButton
	Sleep 1
}

**Comment by eculipseNamae** [comment]
oh i see, I tried doing it and was able to perform it to some degree but very hard to do consistently. This is a pretty good shiro tech, makes shiro top tier.

Thank you for answering! A little late but happy new year!
