### ISSUE TITLE
How does any of the numpad keys work?

### ISSUE THREAD

**Issue by Phatlynx** [Kramar1337/Tower-of-Fantasy-AHK-flex#3]
Hello, great work. How does the numpad keys work? I can't see to get them to work. Could you do a guide?

**Comment by Kramar1337** [comment]
"Numpad 0-9" select macro
"V - Macro Key" activate macro
If "Numpad 0-9" does not work, then you need to press "NumLock" to activate the additional Numpad keyboard (the light on the keyboard will light up). If you have a special keyboard without a block of additional "Numpad" keys, then you can open "data\tofuConfig.ini" and configure another key.

; OFF
key_LabelNumpad0=Numpad0

; AutoAttack
key_LabelNumpad1=Numpad1

; InventoryClicker
key_LabelNumpad2=Numpad2

; AutoFly
key_LabelNumpad3=Numpad3

; MerylAirAttack
key_LabelNumpad4=Numpad4

; MerylAirAttack2
key_LabelNumpad5=Numpad5

; FRIGG Shift+Click
key_LabelNumpad6=Numpad6

; Bhop
key_LabelNumpad7=Numpad7

; SamirDashAttackCancels
key_LabelNumpad8=Numpad8

; Samir Vertical Flight, (Rising Plunge Attack Cancels)
key_LabelNumpad9=Numpad9

; Diluc Vertical Flight
key_LabelNumpadAdd=NumpadAdd
