### ISSUE TITLE
Макрос на Руби

### ISSUE THREAD

**Issue by Herokugitprog** [Kramar1337/Tower-of-Fantasy-AHK-flex#30]
if FIXchat 	;Если "FIXchat" то чекать курсор
{
	if FuncCursorVisible() 	;Если есть курсор то возврат
		Return
}
Loop
{
    GetKeyState, SpaceStateAA, %key_animcancel%, P
    If SpaceStateAA = U
        break

	SendInput {vk1 up}
	Sleep 0
	SendInput {vk1 down}
	Sleep 0
	SendInput {vk1 up}
	Sleep 398
	SendInput {vk32 down} ;глайдер 
	Sleep 0
	SendInput {vk32 up}
	
	; TickCountTimer := A_TickCount
	; SoundBeep
	; TickCountTimerEnd := A_TickCount - TickCountTimer
}
GetKeyState, SpaceStateAA, vk1
If SpaceStateAA = D
	SendInput {vk1 up}
Return

**Comment by Kramar1337** [comment]
добавил, проверяй.
Numpad 5 -  RubyAA
Руби нету, не хотел покупать на фанпее акк для тестов, к тому же тесты с кактусом и тесты в данже против мобов это разные вещи. если чтото криво работает то можешь вручную потыкать тайминги(и мне сюда скинуть):
Lib\LibNumpadSlot.ahk
725 строка или поиск по тексту "Label_Goto_Ruby1:"

задержки меньше 1 мс (AHK не может меньше 15мс) не рекомендуется ставить

**Comment by Herokugitprog** [comment]
SendInput {vk1 up}
Sleep 398
SendInput {vk32 down} ;глайдер

Sleep 398 это минимальная задержка(по крайней мере у меня) если меньше ставить начинает некорректно работать.

**Comment by Herokugitprog** [comment]
Немного переделал 

Label_Goto_Ruby1:
if FIXchat 	;Если "FIXchat" то чекать курсор
{
	if FuncCursorVisible() 	;Если есть курсор то возврат
		Return
}
Sleep 1
;Skill+Dodge + Doli + bounce 
SendInput {vk1}
Sleep 180
SendInput {vk31}
Sleep 400
SendInput {vkA0}
Sleep 180
SendInput {vk1}
Sleep 400
SendInput {vk1}
Sleep 180
SendInput {vk20}
Sleep 180
SendInput {vk20}
Loop
{
    GetKeyState, SpaceStateAA1, %key_animcancel%, P
    If SpaceStateAA1 = U
        break

SendInput {vk1}
Sleep 400
SendInput {%key_flyhackGajetKey%} ;глайдер 


		if ScRandomTime 	;Рандомизатор
			ScRandomizatorFunc()
}

	GetKeyState, SpaceStateAAA, vk1
	If SpaceStateAAA = D
		SendInput, {vk1 Down}
return
