### ISSUE TITLE
Tian dash macro?

### ISSUE THREAD

**Issue by kevinhaeni** [Kramar1337/Tower-of-Fantasy-AHK-flex#31]
Hi! Great work on this library! Would it be possible to add a tian lang dash spam macro?
I tried myself but it doesn't seem to work very well :(

Loop
{
		GetKeyState, SpaceStateAA, %key_animcancel%, P
		If SpaceStateAA = U
			break
	SendInput, {vk2} 	;RButton
	Sleep 50		
	SendInput, {vk1} 	;LButton
	Sleep 120
	if ScRandomTime 	;Рандомизатор
			ScRandomizatorFunc()
		GetKeyState, SpaceStateAA, %key_animcancel%, P
		If SpaceStateAA = U
			break
	SendInput, {vk2} 	;RButton
	Sleep 30
}
    GetKeyState, SpaceStateAA, vk1
    If SpaceStateAA = D
		SendInput, {vk1 Up}
Return

**Comment by Kramar1337** [comment]
update and check
I added a macro but didn't check the damage. I don't know how effective it is
Numpad 4 -  TianDash

**Comment by kevinhaeni** [comment]
Thx a lot man, looks good!
