### ISSUE TITLE
auto fishing mouse click slightly off

### ISSUE THREAD

**Issue by eculipseNamae** [Kramar1337/Tower-of-Fantasy-AHK-flex#33]
The mouse click when fish goes left is slightly off.
![mousecursor](https://user-images.githubusercontent.com/69389203/217127074-10c42be0-281d-46e8-ab8c-7ffc0a5a85e5.jpg)

**Comment by Kramar1337** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/73392036/217281728-f18b929b-0b4c-4650-baeb-2c297e0cfa5a.jpg)
capture area is larger, mouse click cannot miss

**Comment by eculipseNamae** [comment]
oh, I see
but I feel like whenever the fish goes left, the "white line" have trouble keeping up with the "yellow bar" compared to when fish goes right.
Maybe the "white line" moves faster if the mouse click is dead center?

**Comment by Kramar1337** [comment]
in the configuration file "data\tofuConfig.ini" there is a parameter "FisCalibration=50"
increase or decrease this value and check the result

**Comment by eculipseNamae** [comment]
alright I'll try it out
