### ISSUE TITLE
Fish catching too early

### ISSUE THREAD

**Issue by djoeni** [Kramar1337/Tower-of-Fantasy-AHK-flex#34]
Sometime when got fish with high endurance whenever endurance at 1 ex. 1/44 it will catch fish resulting fail (light blue indicator endurance so small). Maybe because i use low graphic preset so that happen.
Any setting that can be change maybe delayed catching whenever endurance goes to 0 ?

**Comment by Kramar1337** [comment]
increased wait by 1 second

**Comment by Kramar1337** [comment]
update and check

**Comment by djoeni** [comment]
thanks
