### ISSUE TITLE
Set Matrix works only for the first weapon

### ISSUE THREAD

**Issue by Revuin** [Kramar1337/Tower-of-Fantasy-AHK-flex#35]
When using F7, the script correctly sets the matrices for the 1st weapon but it does not correctly go to the 2nd weapon's matrices. In this screenshot, it's clicking the 1st red square instead of the 2nd red square where the matrixes button is.

I did more testing and F6 works.

![image](https://user-images.githubusercontent.com/20654538/218934298-d1535b67-ba60-4483-8558-d87306c9dad2.png)

**Comment by Kramar1337** [comment]
I forgot to add a 1500ms game freeze delay. Fixed, check

**Comment by Kramar1337** [comment]
in China in the next patch will add the ability to switch presets. on the global version, this will not happen soon.
