### ISSUE TITLE
Fishing not working.

### ISSUE THREAD

**Issue by Crouw** [Kramar1337/Tower-of-Fantasy-AHK-flex#37]
For a friend of mine the afk fishing isn't working. He does throw bait but the fishing itself (keeping it inside the yellow block) doesn't work at all. Any suggestions?

**Comment by KEKQUEEN** [comment]
Did you manage to fix it?
У меня такая же проблема! И вылов начинается не сразу, а после команды антиафк (может так и должно быть?) При первом запуске все работало, а на следующий день вот это началось. Пробовал менять разрешение, настройки графики, предложенные варианты в описании.

**Comment by KEKQUEEN** [comment]
Did you manage to fix it?

**Comment by Crouw** [comment]
Yeah, he just made some mistakes bc he used geforce programm with it, he found it by himself.
