### ISSUE TITLE
Рыбалка не работает

### ISSUE THREAD

**Issue by KEKQUEEN** [Kramar1337/Tower-of-Fantasy-AHK-flex#38]
У меня проблема с авторыбалкой. Сам заброс происходит не сразу, а после команды антиафк (может так и должно быть?) И после заброса ничего не происходит, если самому нажимать <<A D>> идет туго, после истощения выносливости рыбу автоматически вылавливает и закидывает снова. При первом запуске все работало, а на следующий день вот это началось. Пробовал менять разрешение, настройки графики, предложенные варианты в описании, ничего не помогает.

**Comment by Kramar1337** [comment]
"при первом запуске работало, а после нет". Скачать заново с стандартными настройками и проверить.
покрутить конфиг

; Рыбалка. Поиск желтой и белой полоски. Диапазон(0-256), 11 норм находит
OttenokFis2=11
; Рыбалка. Калибровка расстояния. Если близко к левому краю то увеличить значение. По умолчанию 20
FisCalibration=50

Какое разрешение экрана(стандартное? 1920-1080р) и соотношение сторон(16-9?)
Игра в фуллскрине? Окно активно? Скрипт не умеет рыбачить в альт-табе.
Скриншот или запись сюда

**Comment by KEKQUEEN** [comment]
Уже скачивал заново, в "tofuConfig.ini" все так и стоит, разрешение экрана стандартное 1920-1080р и соотношение сторон 16-9, игра в фуллскрине.
![image](https://user-images.githubusercontent.com/132677587/236643727-6ce47adf-512c-4563-b655-740a4e7e0276.png)
![image](https://user-images.githubusercontent.com/132677587/236643731-8c01a71d-3cc2-485a-8f67-54b1ce7a09be.png)

**Comment by Kramar1337** [comment]
го дискорд демонстрацию экрана
Kramar228#3764
