### ISSUE TITLE
Not Relly Issues but if you can put it Its willl be good

### ISSUE THREAD

**Issue by Matan526** [Kramar1337/Tower-of-Fantasy-AHK-flex#4]
The Trick with Crew class
when you do Jump and Open Jetpack and Left Click this Make Spin Stab and make this Repate this DMG so good!
if you can make macro for this it will be good : - ))

**Comment by Kramar1337** [comment]
did not understand anything, the translator translated through the ass. Can I have a video demonstration? what the script should do and what the character should do.

**Comment by Matan526** [comment]
https://youtu.be/a_TARRY8Yc0?t=71

look on time 1:10

**Comment by Matan526** [comment]
https://youtu.be/z775zEEcUII?t=729

12:10 in Russia

**Comment by Kramar1337** [comment]
the script has already been added. but has not been tested, if the server is overloaded then the animation breaks.

V - Macro Key
Alt + Numpad 2 - Karasuma drill (Test)

don't forget the bind glider "data\tofuConfig.ini"
https://github.com/Kramar1337/Tower-of-Fantasy-AHK-flex/wiki/EN

**Comment by Matan526** [comment]
Karmar 
![תמונה](https://user-images.githubusercontent.com/45513407/187231985-31ca795b-6391-4410-9686-7edba07d11b1.png)

i put Bind Glider and not works. maybe i do something wrong haha

**Comment by Kramar1337** [comment]
; key_flyhackGajetKey is the name of the key on which the "glider/wings/jetpack" gadget is binned
; In the game, by default, the button is "2" (vk32) or "3" (vk33), I have rebinded to "R" (vk52)
; It is better to use virtual codes for compatibility, but regular button names are also possible
; The folder contains data\debug\VirtualCodeKeys.ahk script for viewing virtual codes (does not work on the mouse)
key_flyhackGajetKey=vk52

**Comment by Kramar1337** [comment]
data\tofuConfig.ini
key_flyhackGajetKey=vk32

**Comment by Matan526** [comment]
Ok , Thanx now its Working: - ))
