### ISSUE TITLE
[Feature Request] Auto close when bait is empty

### ISSUE THREAD

**Issue by djoeni** [Kramar1337/Tower-of-Fantasy-AHK-flex#40]
Please add feature for auto close game and AHK when bait is empty/run out. Better yet if there is option to auto shutdown pc too.

Thanks.

**Comment by Kramar1337** [comment]
I don't play TOF anymore. The script will not be supplemented or changed.
It takes about 3 hours to work out 350 units of bait. You can set an alarm:
Press Windows + R (Run)
Shut down computer after 3 hours:
shutdown -s -f -t 7200
Cancel Shutdown:
shutdown -a
