### ISSUE TITLE
Проблема с  FrontierClash

### ISSUE THREAD

**Issue by illussionn** [Kramar1337/Tower-of-Fantasy-AHK-flex#41]
Добрый день, давно я скачивал ваш AHK для поднятия уровня с помощью FC, но недавно скачав снова я наткнулся на проблему. Для того чтобы запустить подбор игроков нужно (скорее всего это добавилось после обновления) выбрать с каким резонансом ты играешь (атк, защита, хил), но когда макрос нажимает на "Подбор игроков" он останавливается на окне где нужно выбрать резонанс, тем самым переставая работать, так как он ждет собрания тимы и подтверждения для входа во фронтир. Прошу помочь, вдруг это я что-то туплю и не правильно настроил.
![Снимок экрана 2023-09-12 172751](https://github.com/Kramar1337/Tower-of-Fantasy-AHK-flex/assets/144803288/aa99ae51-5b46-404c-8fc3-d5a0a443a625)

**Comment by Kramar1337** [comment]
обновил, проверяй
