### ISSUE TITLE
Проблема с FrontierClash

### ISSUE THREAD

**Issue by SKeLeToNya** [Kramar1337/Tower-of-Fantasy-AHK-flex#42]
Доброго времени.
При долгом поиске фронтира бывает так, что скрипт приёма игры срабатывает не на плашку принять игру а на что-то другое. Или просто срабатывает по таймауту. Непонятно. Пример несработавшегоскрипт уже как 40 секунд прожал асепт, а найденная игра появилась только пару секунд назад.
![image](https://github.com/Kramar1337/Tower-of-Fantasy-AHK-flex/assets/8065397/d8c70add-a44c-47af-972a-990b1a9390a0)

**Comment by SKeLeToNya** [comment]
upd
на 55м цикле ожидания асепта - он скипает асепт фазу и считает что мы в данже.
Я так понимаю для себя можно вот тут ему увеличить кол-во циклов пока вы придумаете что с этим сделать кроме как захардкодить? 
![image](https://github.com/Kramar1337/Tower-of-Fantasy-AHK-flex/assets/8065397/f30b5bfe-fec5-4866-bd74-754e23c66f70)

**Comment by Kramar1337** [comment]
добавил 20 мин, думаю за это время найдется пати.
