### ISSUE TITLE
Можно использовать как афк бота?

### ISSUE THREAD

**Issue by Jake093** [Kramar1337/Tower-of-Fantasy-AHK-flex#5]
Исходя из функционала так и не понял, возможно ли использовать скрипт как афк бота для фарма или нет?

**Comment by Kramar1337** [comment]
https://github.com/Kramar1337/Tower-of-Fantasy-AHK-flex/wiki/RU

**Comment by Kramar1337** [comment]
F4 - *Слот под специфические макросы

Тут будут лежать редкие, бесполезные, специфические макросы. Некоторые макросы могут работать с свернутым окном. Зашел в игру нажал "F4", обрезал FPS (например RTSS, 10FPS норм) и пошел играть в другую игру. VLC плеер почему-то конфликтует. В игры с хорошим античитом не рекомендую идти.

Открываем "data\tofuConfig.ini" настраиваем дефолтный макрос по умолчанию "OldMacroBackVar=1"

0 - Отключить
1 - AFK фермерство, спам "F" каждые 5 сек
2 - AFK ачивка сёрфера, залипание кнопки "W" и "A"
3 - AFK фермерство на Хильде, спам "Click" каждые 5 сек
4 - AFK фермерство, спам "F" залипание кнопки "W" и "A". Гранатная ферма(-75, -845)
Специфические макросы можно переключать "Alt + Up" и "Alt + Down" (стрелки на клавиатуре)

**Comment by Jake093** [comment]
Так а если я запущу спам F, фермерство, и включу автобег, как он сам найдет, что открывать надо? Я че-то не до конца понимаю

**Comment by Kramar1337** [comment]
сча все объясню летишь сюда "-75, -845" там 3 кустика растут. Садишься на корты, разворачиваешь камеру так чтобы скрипт ходил по кругу и собирал ягоды, нажимаешь кнопку "F4" и смотришь как персонаж ходит, если цепляет все 3 куста то можно сворачивать игру, дальше скрипт сам играет

**Comment by Kramar1337** [comment]
просто придумай сам как это можно использовать, название функции скрипта говорит за себя, скрипт не будет играть за тебя и качать аккаунт, это простой спам кнопок.
