### ISSUE TITLE
AFK Frontier Clash when Apex Lague Unactive

### ISSUE THREAD

**Issue by darkero27** [Kramar1337/Tower-of-Fantasy-AHK-flex#7]
Can you added more whe apex lague is unactive? because i used now but it clicked Void Rift

**Comment by Kramar1337** [comment]
I don't want to add a timer tied to the clock. Added manual selection before applying
![image](https://user-images.githubusercontent.com/73392036/188653674-df8a2199-a0d6-46bc-bed7-2da6e64f77b5.png)
