### ISSUE TITLE
Запрос функций / Features Request

### ISSUE THREAD

**Issue by RXDCODX** [Kramar1337/Tower-of-Fantasy-AHK-flex#8]
1. Привязать работу макросов/скриптов, в том числе их активацию, к окну игры, чтобы когда активно другое окно как например браузер хром то макросы не активировались
2. Добавить макрос с чарджем после двух лкм атак

**Comment by Kramar1337** [comment]
часть клавиш привязаны к окну игры, чтобы не мешать, но F1, F2, F3, F4, F9 я спецом не ставил фильтр. нампад кнопки не фильтруются, ими в принципе никто не пользуется я и забил.
макрос на холд тычки могу добавить но... на разных персонажах разная анимация... я пробовал, херня получается
на каком персонаже тестить холды?

**Comment by RXDCODX** [comment]
У немезиды 2 аа и после чардж, хотелось бы еще на кубана фулл чардж в 5 аа атак потом снова фулл чардж в 5 аа

**Comment by Kramar1337** [comment]
на нампад повесил фильтры
добавил немезиду
Alt + Numpad 3 - Nemesis 2NH
на кубе не играю, если бы был видос, я не очень понял что за фулл чарж 5
