### ISSUE TITLE
suggestion add relic combo

### ISSUE THREAD

**Issue by chaderfooster** [Kramar1337/Tower-of-Fantasy-AHK-flex#9]
Good morning, I would like to ask if you could add a combo of relics by one key, to use multiple relics.

I live in Brazil, great job.

**Comment by Kramar1337** [comment]
Hi
This might be a good idea. But there's a problem. Many relics have a cast animation, so you won't be able to use 6 relics at the same time. Different players can have different relics (different levels of enhancement), each player collects according to their playstyle and uses relics in their own way.

It is impossible to make a universal script that will ideally use all relics.
